
VCS_INC_FILE_NAME = $(MCASH_HOME)/synthesis/include/mcash_config.v
CPP_INC_FILE_NAME = $(MCASH_HOME)/golden/include/mcash_para.h

all:
	python3 process_conf.py $(VCS_INC_FILE_NAME) $(CPP_INC_FILE_NAME)
