import configparser

sv_conf_list = []

config = configparser.ConfigParser()
config.optionxform = str
config.read('mcash_conf.ini')

sv_conf_list.append('// This system verilog config file is generated by python.')

for section_name in config.sections():
  section = config[section_name]
  sv_conf_list.append(f"// {section_name}")
  for k, v in section.items():
    sv_conf_list.append(f"`define {k} {v}")


with open('mcash_config.svh', 'w') as f:
  f.writelines(line + '\n' for line in sv_conf_list)