// This verilog config file is generated by python.
// MCASH_CONFIG
`define CHANNLE_SIZE 3
`define BANK_SIZE 4
// CROSS_BAR_CONFIG
`define XBAR_BUFFER_SIZE 5
`define XBAR_ROB_SIZE 8
// BANK_CONFIG
`define ISU_IQ_PTR_WIDTH 6
`define ISU_IQ_SIZE 64
