// This system verilog config file is generated by python.
// CROSS_BAR_CONFIG
`define CROSS_BAR_CORE_BUFFER_SIZE 5
`define CROSS_BAR_ROB_SIZE 8
// BANK_CONFIG
`define BANK_IQ_PTR_WIDTH 6
`define BANK_IQ_SIZE 64
